// This file is automatically generated. Do not edit manually.
// Updated for ultimate lesson builder schema, tagging, scoring, and feedback tables.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      aircraft: {
        Row: {
          category: string
          class: string
          created_at: string | null
          hobbs_time: number
          id: string
          is_active: boolean | null
          is_complex: boolean | null
          is_high_performance: boolean | null
          is_tailwheel: boolean | null
          last_inspection_date: string
          make: string
          model: string
          tail_number: string
          updated_at: string | null
          year: number
        }
        Insert: {
          category: string
          class: string
          created_at?: string | null
          hobbs_time: number
          id?: string
          is_active?: boolean | null
          is_complex?: boolean | null
          is_high_performance?: boolean | null
          is_tailwheel?: boolean | null
          last_inspection_date: string
          make: string
          model: string
          tail_number: string
          updated_at?: string | null
          year: number
        }
        Update: {
          category?: string
          class?: string
          created_at?: string | null
          hobbs_time?: number
          id?: string
          is_active?: boolean | null
          is_complex?: boolean | null
          is_high_performance?: boolean | null
          is_tailwheel?: boolean | null
          last_inspection_date?: string
          make?: string
          model?: string
          tail_number?: string
          updated_at?: string | null
          year?: number
        }
        Relationships: []
      }
      availability_blocks: {
        Row: {
          created_at: string | null
          end_time: string
          id: string
          reason: string | null
          recurrence_rule: string | null
          start_time: string
          updated_at: string | null
          user_id: string
          user_type: string
        }
        Insert: {
          created_at?: string | null
          end_time: string
          id?: string
          reason?: string | null
          recurrence_rule?: string | null
          start_time: string
          updated_at?: string | null
          user_id: string
          user_type: string
        }
        Update: {
          created_at?: string | null
          end_time?: string
          id?: string
          reason?: string | null
          recurrence_rule?: string | null
          start_time?: string
          updated_at?: string | null
          user_id?: string
          user_type?: string
        }
        Relationships: []
      }
      calendar_integrations: {
        Row: {
          access_token: string
          created_at: string | null
          expires_at: string | null
          id: string
          provider: string
          refresh_token: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          access_token: string
          created_at?: string | null
          expires_at?: string | null
          id?: string
          provider: string
          refresh_token?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          access_token?: string
          created_at?: string | null
          expires_at?: string | null
          id?: string
          provider?: string
          refresh_token?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      core_topics: {
        Row: {
          description: string | null
          id: string
          name: string
        }
        Insert: {
          description?: string | null
          id?: string
          name: string
        }
        Update: {
          description?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      document_types: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          name: string
          requires_expiration: boolean | null
          requires_verification: boolean | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          name: string
          requires_expiration?: boolean | null
          requires_verification?: boolean | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          requires_expiration?: boolean | null
          requires_verification?: boolean | null
          updated_at?: string | null
        }
        Relationships: []
      }
      documents: {
        Row: {
          created_at: string | null
          description: string | null
          document_type: string
          expiration_date: string | null
          file_path: string
          file_type: string
          id: string
          is_verified: boolean | null
          title: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          document_type: string
          expiration_date?: string | null
          file_path: string
          file_type: string
          id?: string
          is_verified?: boolean | null
          title: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          description?: string | null
          document_type?: string
          expiration_date?: string | null
          file_path?: string
          file_type?: string
          id?: string
          is_verified?: boolean | null
          title?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "documents_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      endorsement_templates: {
        Row: {
          category: string | null
          code: string
          created_at: string
          ecfr_link: string | null
          explanation: string | null
          faa_reference: string | null
          id: string
          tags: string[] | null
          template_text: string
          title: string
          updated_at: string
        }
        Insert: {
          category?: string | null
          code: string
          created_at?: string
          ecfr_link?: string | null
          explanation?: string | null
          faa_reference?: string | null
          id?: string
          tags?: string[] | null
          template_text: string
          title: string
          updated_at?: string
        }
        Update: {
          category?: string | null
          code?: string
          created_at?: string
          ecfr_link?: string | null
          explanation?: string | null
          faa_reference?: string | null
          id?: string
          tags?: string[] | null
          template_text?: string
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      endorsements: {
        Row: {
          created_at: string | null
          date_issued: string
          description: string
          endorsement_type: string
          expiration_date: string | null
          id: string
          instructor_id: string
          reference: string | null
          status: string
          student_id: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          date_issued: string
          description: string
          endorsement_type: string
          expiration_date?: string | null
          id?: string
          instructor_id: string
          reference?: string | null
          status?: string
          student_id: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          date_issued?: string
          description?: string
          endorsement_type?: string
          expiration_date?: string | null
          id?: string
          instructor_id?: string
          reference?: string | null
          status?: string
          student_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "endorsements_instructor_id_fkey"
            columns: ["instructor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "endorsements_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      errors: {
        Row: {
          description: string | null
          id: string
          name: string
        }
        Insert: {
          description?: string | null
          id?: string
          name: string
        }
        Update: {
          description?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      faa_requirements: {
        Row: {
          certificate_type: string
          created_at: string | null
          description: string
          id: string
          minimum_value: number | null
          reference: string
          requirement_type: string
          updated_at: string | null
        }
        Insert: {
          certificate_type: string
          created_at?: string | null
          description: string
          id?: string
          minimum_value?: number | null
          reference: string
          requirement_type: string
          updated_at?: string | null
        }
        Update: {
          certificate_type?: string
          created_at?: string | null
          description?: string
          id?: string
          minimum_value?: number | null
          reference?: string
          requirement_type?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      flight_log_entries: {
        Row: {
          aircraft_id: string
          complex_time: number | null
          created_at: string | null
          cross_country_time: number | null
          date: string
          dual_given: number | null
          dual_received: number | null
          flight_session_id: string | null
          high_performance_time: number | null
          id: string
          instructor_id: string | null
          instrument_time: number | null
          landings_day: number | null
          landings_night: number | null
          multi_engine_time: number | null
          night_time: number | null
          pic_time: number | null
          remarks: string | null
          sic_time: number | null
          simulator_time: number | null
          solo_time: number | null
          student_id: string
          tailwheel_time: number | null
          total_time: number
          updated_at: string | null
        }
        Insert: {
          aircraft_id: string
          complex_time?: number | null
          created_at?: string | null
          cross_country_time?: number | null
          date: string
          dual_given?: number | null
          dual_received?: number | null
          flight_session_id?: string | null
          high_performance_time?: number | null
          id?: string
          instructor_id?: string | null
          instrument_time?: number | null
          landings_day?: number | null
          landings_night?: number | null
          multi_engine_time?: number | null
          night_time?: number | null
          pic_time?: number | null
          remarks?: string | null
          sic_time?: number | null
          simulator_time?: number | null
          solo_time?: number | null
          student_id: string
          tailwheel_time?: number | null
          total_time: number
          updated_at?: string | null
        }
        Update: {
          aircraft_id?: string
          complex_time?: number | null
          created_at?: string | null
          cross_country_time?: number | null
          date?: string
          dual_given?: number | null
          dual_received?: number | null
          flight_session_id?: string | null
          high_performance_time?: number | null
          id?: string
          instructor_id?: string | null
          instrument_time?: number | null
          landings_day?: number | null
          landings_night?: number | null
          multi_engine_time?: number | null
          night_time?: number | null
          pic_time?: number | null
          remarks?: string | null
          sic_time?: number | null
          simulator_time?: number | null
          solo_time?: number | null
          student_id?: string
          tailwheel_time?: number | null
          total_time?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "flight_log_entries_aircraft_id_fkey"
            columns: ["aircraft_id"]
            isOneToOne: false
            referencedRelation: "aircraft"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "flight_log_entries_flight_session_id_fkey"
            columns: ["flight_session_id"]
            isOneToOne: false
            referencedRelation: "flight_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      flight_sessions: {
        Row: {
          aircraft_id: string
          created_at: string | null
          date: string
          end_time: string | null
          enrollment_id: string
          hobbs_end: number
          hobbs_start: number
          id: string
          instructor_id: string
          lesson_id: string
          location_id: string | null
          notes: string | null
          postbrief_minutes: number | null
          prebrief_minutes: number | null
          recurrence_rule: string | null
          request_status: string | null
          requested_by: string | null
          session_type: string | null
          start_time: string | null
          status: string
          updated_at: string | null
          weather_conditions: Json | null
        }
        Insert: {
          aircraft_id: string
          created_at?: string | null
          date: string
          end_time?: string | null
          enrollment_id: string
          hobbs_end: number
          hobbs_start: number
          id?: string
          instructor_id: string
          lesson_id: string
          location_id?: string | null
          notes?: string | null
          postbrief_minutes?: number | null
          prebrief_minutes?: number | null
          recurrence_rule?: string | null
          request_status?: string | null
          requested_by?: string | null
          session_type?: string | null
          start_time?: string | null
          status?: string
          updated_at?: string | null
          weather_conditions?: Json | null
        }
        Update: {
          aircraft_id?: string
          created_at?: string | null
          date?: string
          end_time?: string | null
          enrollment_id?: string
          hobbs_end?: number
          hobbs_start?: number
          id?: string
          instructor_id?: string
          lesson_id?: string
          location_id?: string | null
          notes?: string | null
          postbrief_minutes?: number | null
          prebrief_minutes?: number | null
          recurrence_rule?: string | null
          request_status?: string | null
          requested_by?: string | null
          session_type?: string | null
          start_time?: string | null
          status?: string
          updated_at?: string | null
          weather_conditions?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "flight_sessions_aircraft_id_fkey"
            columns: ["aircraft_id"]
            isOneToOne: false
            referencedRelation: "aircraft"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "flight_sessions_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "student_enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "flight_sessions_instructor_id_fkey"
            columns: ["instructor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "flight_sessions_lesson_id_fkey"
            columns: ["lesson_id"]
            isOneToOne: false
            referencedRelation: "syllabus_lessons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "flight_sessions_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          email: string
          first_name: string
          last_name: string
          role: string
          avatar_url: string | null
          phone: string | null
          bio: string | null
        }
        Insert: {
          id: string
          created_at?: string
          updated_at?: string
          email: string
          first_name: string
          last_name: string
          role: string
          avatar_url?: string | null
          phone?: string | null
          bio?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          email?: string
          first_name?: string
          last_name?: string
          role?: string
          avatar_url?: string | null
          phone?: string | null
          bio?: string | null
        }
      }
      syllabi: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          title: string
          description: string
          faa_type: string
          version: string
          is_active: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          title: string
          description: string
          faa_type: string
          version: string
          is_active?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          title?: string
          description?: string
          faa_type?: string
          version?: string
          is_active?: boolean
        }
      }
      syllabus_lessons: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          syllabus_id: string
          title: string
          description: string
          order_index: number
          lesson_type: string
          estimated_hours: number
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          syllabus_id: string
          title: string
          description: string
          order_index: number
          lesson_type: string
          estimated_hours: number
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          syllabus_id?: string
          title?: string
          description?: string
          order_index?: number
          lesson_type?: string
          estimated_hours?: number
        }
      }
      maneuvers: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          name: string
          description: string
          faa_reference: string
          category: string
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          name: string
          description: string
          faa_reference: string
          category: string
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          name?: string
          description?: string
          faa_reference?: string
          category?: string
        }
      }
      lesson_maneuvers: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          lesson_id: string
          maneuver_id: string
          is_required: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          lesson_id: string
          maneuver_id: string
          is_required?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          lesson_id?: string
          maneuver_id?: string
          is_required?: boolean
        }
      }
      student_enrollments: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          student_id: string
          syllabus_id: string
          instructor_id: string
          start_date: string
          target_completion_date: string | null
          completion_date: string | null
          status: string
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          student_id: string
          syllabus_id: string
          instructor_id: string
          start_date: string
          target_completion_date?: string | null
          completion_date?: string | null
          status?: string
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          student_id?: string
          syllabus_id?: string
          instructor_id?: string
          start_date?: string
          target_completion_date?: string | null
          completion_date?: string | null
          status?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      flight_sessions: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          enrollment_id: string
          lesson_id: string
          instructor_id: string
          aircraft_id: string
          date: string
          start_time: string
          end_time: string
          hobbs_start: number
          hobbs_end: number
          status: string
          notes: string | null
          weather_conditions: Json | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          enrollment_id: string
          lesson_id: string
          instructor_id: string
          aircraft_id: string
          date: string
          start_time: string
          end_time: string
          hobbs_start: number
          hobbs_end: number
          status?: string
          notes?: string | null
          weather_conditions?: Json | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          enrollment_id?: string
          lesson_id?: string
          instructor_id?: string
          aircraft_id?: string
          date?: string
          start_time?: string
          end_time?: string
          hobbs_start?: number
          hobbs_end?: number
          status?: string
          notes?: string | null
          weather_conditions?: Json | null
        }
      }
      maneuver_scores: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          flight_session_id: string
          maneuver_id: string
          score: number
          notes: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          flight_session_id: string
          maneuver_id: string
          score: number
          notes?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          flight_session_id?: string
          maneuver_id?: string
          score?: number
          notes?: string | null
        }
      }
      documents: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          user_id: string
          title: string
          description: string | null
          file_path: string
          file_type: string
          document_type: string
          expiration_date: string | null
          is_verified: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          user_id: string
          title: string
          description?: string | null
          file_path: string
          file_type: string
          document_type: string
          expiration_date?: string | null
          is_verified?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          user_id?: string
          title?: string
          description?: string | null
          file_path?: string
          file_type?: string
          document_type?: string
          expiration_date?: string | null
          is_verified?: boolean
        }
      }
      endorsements: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          student_id: string
          instructor_id: string
          endorsement_type: string
          description: string
          date_issued: string
          expiration_date: string | null
          reference: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          student_id: string
          instructor_id: string
          endorsement_type: string
          description: string
          date_issued: string
          expiration_date?: string | null
          reference?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          student_id?: string
          instructor_id?: string
          endorsement_type?: string
          description?: string
          date_issued?: string
          expiration_date?: string | null
          reference?: string | null
        }
      }
      faa_requirements: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          certificate_type: string
          requirement_type: string
          description: string
          reference: string
          minimum_value: number | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          certificate_type: string
          requirement_type: string
          description: string
          reference: string
          minimum_value?: number | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          certificate_type?: string
          requirement_type?: string
          description?: string
          reference?: string
          minimum_value?: number | null
        }
      }
      student_requirements: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          student_id: string
          requirement_id: string
          current_value: number
          is_complete: boolean
          completion_date: string | null
          verified_by: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          student_id: string
          requirement_id: string
          current_value?: number
          is_complete?: boolean
          completion_date?: string | null
          verified_by?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          student_id?: string
          requirement_id?: string
          current_value?: number
          is_complete?: boolean
          completion_date?: string | null
          verified_by?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
