'use client'
import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"

export default function PreviewEmailPanel({ lessonInfo, maneuvers, coreTopics, resources, whatToBring }: {
  lessonInfo: any,
  maneuvers: any[],
  coreTopics: any[],
  resources: any[],
  whatToBring: any[],
}) {
  const [mode, setMode] = useState<'preview' | 'email'>('preview')

  function renderPreview() {
    return (
      <div className="space-y-6">
        <Card className="p-6">
          <h2 className="text-2xl font-bold mb-2">{lessonInfo.title || 'Lesson Title'}</h2>
          <div className="mb-2 text-muted-foreground">{lessonInfo.objectives || 'Lesson objectives go here.'}</div>
          <Separator className="my-4" />
          <div>
            <h3 className="font-semibold mb-1">Maneuvers</h3>
            <div className="flex flex-wrap gap-2 mb-2">
              {maneuvers.length ? maneuvers.map((m) => (
                <Badge key={m.id}>{m.name}</Badge>
              )) : <span className="text-gray-400">None</span>}
            </div>
            {maneuvers.map((m) => m.instructor_notes && (
              <div key={m.id + '-notes'} className="text-sm text-muted-foreground mb-1">{m.name}: {m.instructor_notes}</div>
            ))}
          </div>
          <Separator className="my-4" />
          <div>
            <h3 className="font-semibold mb-1">Core Topics</h3>
            <div className="flex flex-wrap gap-2 mb-2">
              {coreTopics.length ? coreTopics.map((t) => (
                <Badge key={t.id}>{t.name}</Badge>
              )) : <span className="text-gray-400">None</span>}
            </div>
            {coreTopics.map((t) => t.annotation && (
              <div key={t.id + '-notes'} className="text-sm text-muted-foreground mb-1">{t.name}: {t.annotation}</div>
            ))}
          </div>
          <Separator className="my-4" />
          <div>
            <h3 className="font-semibold mb-1">Resources</h3>
            <ul className="list-disc ml-6">
              {resources.length ? resources.map((r) => (
                <li key={r.id}><a href={r.link} className="text-blue-600 underline" target="_blank" rel="noopener noreferrer">{r.title}</a>{r.annotation && <> — <span className="text-muted-foreground">{r.annotation}</span></>}</li>
              )) : <span className="text-gray-400">None</span>}
            </ul>
          </div>
          <Separator className="my-4" />
          <div>
            <h3 className="font-semibold mb-1">What to Bring</h3>
            <ul className="list-disc ml-6">
              {whatToBring.length ? whatToBring.map((i) => (
                <li key={i.id}>{i.name}{i.annotation && <> — <span className="text-muted-foreground">{i.annotation}</span></>}</li>
              )) : <span className="text-gray-400">None</span>}
            </ul>
          </div>
        </Card>
      </div>
    )
  }

  function renderEmail() {
    return (
      <div className="bg-white p-6 rounded shadow max-w-2xl mx-auto border">
        <h2 style={{ fontSize: 22, fontWeight: 'bold', marginBottom: 8 }}>{lessonInfo.title || 'Lesson Title'}</h2>
        <div style={{ marginBottom: 12, color: '#666' }}>{lessonInfo.objectives || 'Lesson objectives go here.'}</div>
        <div style={{ marginBottom: 12 }}><b>Maneuvers:</b> {maneuvers.map(m => m.name).join(', ') || 'None'}</div>
        <div style={{ marginBottom: 12 }}><b>Core Topics:</b> {coreTopics.map(t => t.name).join(', ') || 'None'}</div>
        <div style={{ marginBottom: 12 }}><b>Resources:</b>
          <ul>
            {resources.length ? resources.map(r => (
              <li key={r.id}><a href={r.link}>{r.title}</a>{r.annotation && ` — ${r.annotation}`}</li>
            )) : <li>None</li>}
          </ul>
        </div>
        <div style={{ marginBottom: 12 }}><b>What to Bring:</b>
          <ul>
            {whatToBring.length ? whatToBring.map(i => (
              <li key={i.id}>{i.name}{i.annotation && ` — ${i.annotation}`}</li>
            )) : <li>None</li>}
          </ul>
        </div>
        <div style={{ marginTop: 24, color: '#888', fontSize: 13 }}>This lesson plan was generated by Desert Skies Aviation Portal.</div>
      </div>
    )
  }

  return (
    <div>
      <div className="flex gap-2 mb-4">
        <Button variant={mode === 'preview' ? 'default' : 'outline'} onClick={() => setMode('preview')}>Live Preview</Button>
        <Button variant={mode === 'email' ? 'default' : 'outline'} onClick={() => setMode('email')}>Email Template</Button>
      </div>
      {mode === 'preview' ? renderPreview() : renderEmail()}
    </div>
  )
} 